### ISSUE TITLE
loading of large files is slow

### ISSUE THREAD

**Issue by GitRedington** [OshkoshScholars/OshkoshScholars#1]
On the SPECTRUM submission sight there is difficulty in loading information under Media (images or text).
Also if more than one in all of these categories could be loaded it would help in ease of use.

**Comment by tkimnguyen** [comment]
What is the difficulty?  (If you want to allow multiple uploads, please create a separate issue for that)

**Comment by GitRedington** [comment]
1.  large zip. files (8MB) take hours to upload.
2. If the other criterion (URL of video or audio and Description file) require more than one file there is no way of uploading them without creating another submission.

**Comment by tkimnguyen** [comment]
(I'm going to split your point 2 out into a new separate issue, #2)

**Comment by tkimnguyen** [comment]
Brian tells me you already have some instructions for video uploads re: uploading to Google or Kaltura, so could we do the same here? i.e.. ask submitters to upload to other service and provide a URL to their uploaded file? The problem here may be also that the form tries to send you an email containing the uploaded file, as an attachment, and it's quite likely that the campus mail server is rejecting such large attachments.

**Comment by tkimnguyen** [comment]
Now that there is a "from" address set ( in #6 ) it could be that submission email confirmations work better.

**Comment by tkimnguyen** [comment]
We could also set max file size limits on the form to ensure that for larger files submitters sent us a URL to the files they uploaded to another service, e.g. Kaltura

**Comment by tkimnguyen** [comment]
Going to close this since we no longer accept huge files (max 100 MB). New Spectrum issues should be filed in https://github.com/OshkoshScholars/Spectrum/issues.
